export default {
    translation: {
      h1RuName: 'RSS агрегатор',
      leadP: 'Начните читать RSS сегодня! Это легко, это красиво.',
      formFloatingDivLabel: 'Ссылка RSS',
      textMutedP: 'Пример: https://www.henneth-annun.ru/',
      btn: 'Добавить',
      textCenter: 'created by ',
      textCenterA: 'Hexlet',
      notOneOf: 'RSS уже существует',
      matches: 'Ссылка должна быть валидным URL',
      notValidRSS: 'Ресурс не содержит валидный RSS',
      successRSS: 'RSS успешно загружен',
      invalidUrl: 'Ссылка должна быть валидным URL',
      isNetworkError: 'Ошибка сети',
      posts: 'Посты',
      viewing: 'Просмотр',
      feeds: 'Фиды',
      btnPrimary: 'Читать полностью',
      btnSecondary: 'Закрыть',
      title: 'Hexlet Frontend Project',
    },
  };